# Generated by Django 4.2.5 on 2023-09-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategoryModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(db_column="category_name", max_length=50),
                ),
                (
                    "category_url_name",
                    models.CharField(
                        blank=True,
                        db_column="category_url_name",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="created_on"),
                ),
            ],
            options={
                "db_table": "product_category",
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "product_name",
                    models.CharField(db_column="product_name", max_length=200),
                ),
                (
                    "product_description",
                    models.TextField(
                        db_column="product_description", verbose_name="description"
                    ),
                ),
                (
                    "manufactured_date",
                    models.DateField(auto_now_add=True, db_column="manufactured_date"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active", default=True, verbose_name="Active"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=3, max_digits=10
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        db_column="slug",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        db_column="categories",
                        related_name="products",
                        to="product.productcategorymodel",
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductImageModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        db_column="images",
                        null=True,
                        upload_to=product.models.ProductImageModel.product_img_path,
                        verbose_name="Display Picture",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
            },
        ),
        migrations.CreateModel(
            name="OrderDetailModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(db_column="quantity")),
                (
                    "total_price",
                    models.DecimalField(
                        db_column="total_price", decimal_places=3, max_digits=10
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="customer name"),
                ),
                ("primary_delivery_address", models.CharField(max_length=100)),
                (
                    "secondary_delivery_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=40)),
                ("ordered_date", models.DateField(auto_now_add=True)),
                (
                    "order_staus",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "CONFIRMED"),
                            ("DISPTACHED", "DISPTACHED"),
                            ("DELIVERED", "DELIVERED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                    ),
                ),
                ("payment_completed", models.BooleanField(default=False)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        db_column="ordered_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_details",
            },
        ),
        migrations.CreateModel(
            name="InventoryModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(db_column="quantity")),
                (
                    "rate",
                    models.DecimalField(
                        db_column="rate", decimal_places=3, max_digits=10
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
    ]
