# Generated by Django 4.2.5 on 2023-09-14 17:07

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimagemodel",
            name="images",
            field=models.ImageField(
                db_column="images",
                upload_to=product.models.ProductImageModel.product_img_path,
                verbose_name="Display Picture",
            ),
        ),
    ]
