# Generated by Django 4.2.5 on 2023-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_orderdetailmodel_order_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetailmodel",
            name="contact_number",
            field=models.CharField(default=986616994, max_length=20),
            preserve_default=False,
        ),
    ]
