# Generated by Django 4.2.5 on 2023-09-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "banner_title",
                    models.CharField(db_column="banner_title", max_length=100),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        db_column="banner_image",
                        upload_to=home.models.BannerImagesModel.banner_directory_path,
                    ),
                ),
                (
                    "banner_redirect_url",
                    models.CharField(
                        blank=True,
                        db_column="banner_redirect_url",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "banner_images",
            },
        ),
        migrations.CreateModel(
            name="MyCart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cart_status",
                    models.BooleanField(db_column="cart_status", default=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productmodel",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cart",
            },
        ),
    ]
